name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
inputs:
  pokemon_id:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: 1
outputs:
  pokemon_name:
    description: 'Name des Pokemons'
    value: ${{ steps.pokemon_name.outputs.pokemon_name }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
       chmod +x ${{ github.action_path }}/test.sh 
       ${{ github.action_path }}/test.sh
      shell: bash
    - id: pokemon_name
      run: echo "::set-output name=pokemon_name::145"
      shell: bash
