name: Matrix

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
         stackName: [ edl-files-loader-infra ,edl-files-loader-app ]
         include:
          - stackName: edl-files-loader-app
            region: us-east-1
            currentEnvName: devl
            s3Bucket: jd-us01-commoninformationservices-devl-system
            fileName: infrastructure/cloudformation_templates/infrastructure-stack.j2
          - stackName: edl-files-loader-app
            lambda: edl-delta-request-handler-lambda
          - stackName: edl-files-loader-app
            lambda: edl-file-ingest-completion-lambda
          - stackName: edl-files-loader-app
            region: us-east-1
            currentEnvName: devl
            s3Bucket: jd-us01-commoninformationservices-devl-system
            fileName: infrastructure/cloudformation_templates/api-stack.j2
 
    steps:
    - name: Deploy and Test - ${{  matrix.config.currentEnvName }} - ${{ matrix.config.stackName }}"
      run: |
         echo ${{ matrix.config.region}}
         echo ${{ matrix.config.currentEnvName}}
         echo ${{ matrix.config.s3Bucket}}
         echo ${{ matrix.config.fileName}}
         echo ${{ matrix.config.stackName}}
         
         
    - name: print1
      run: |
         echo ${{ matrix.lambda}}
