name: Matrix

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
       stackName: [edl-files-loader-infra,edl-files-loader-app]    
       lambda: [ edl-delta-request-handler-lambda, edl-file-ingest-completion-lambda ]
       exclude: 
       - stackName: edl-files-loader-infra
         lambda: edl-delta-request-handler-lambda
       - stackName: edl-files-loader-infra
         lambda: edl-file-ingest-completion-lambda 
       
        
    steps:
    - name: Deploy and Test - ${{ matrix.stackName }}"
      run: |

         echo ${{ matrix.config.stackName}}
         
         
    - name: print1
      if: contains(matrix.lambda, 'lambda')
      run: |
         echo ${{ matrix.lambda}}
