name: test

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       fruit: [apple, pear]
    steps:
    name: print
    run: echo ${{ matrix.fruit }}
