name: Matrix

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"FOO\":["abc"],\"BAR\":["xyz"]}"
         
         
    - name: print1
      run: |
         echo ${{ steps.set-matrix.outputs.matrix }}
