name: Matrix

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
       devl: [us-east-1,devl,jd-us01-commoninformationservices-devl-system,infrastructure/cloudformation_templates/infrastructure-stack.j2 , edl-files-loader-infra ]
       include:
        - devl: edl-files-loader-infra 
          lambda: edl-delta-request-handler-lambda 
    steps:
    - name: Deploy and Test - ${{  matrix.devl }} - ${{ matrix.devl}}"
      run: |
         echo ${{ matrix.region}}
         echo ${{ matrix.currentEnvName}}
         echo ${{ matrix.s3Bucket}}
         echo ${{ matrix.fileName}}
         echo ${{ matrix.stackName}}
         
         
    - name: print1
      run: |
         echo ${{ matrix.lambda}}
