name: test pull request
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'devl'
        required: true
        default: 'devl'
jobs:
 BuildAndTest:
   runs-on: ubuntu-latest 
   steps:
    - uses: actions/checkout@v2
    - name: Build Deployment
      run: |
        echo BuildTest
 DevDeploy:
   runs-on: ubuntu-latest 
   if: ${{ (github.event.ref == 'refs/heads/master' || github.event.inputs.environment == 'devl') }}
   needs: [BuildAndTest]
   steps:
    - uses: actions/checkout@v2
    - name: Build Deployment
      run: |
        echo Devl Deployment 
 ProdDeploy:
    if: ${{ github.event.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest 
    needs: [BuildAndTest,DevDeploy]
    steps:
    - uses: actions/checkout@v2
    - run: echo Prod Deployment
    - name: Get commitId
      id: commitId
      run: echo "::set-output name=commitId::$(git log -n 1 --pretty=format:'%h')"
    - run: echo ${{ steps.commitId.outputs.commitId }}
    - run: echo https://github.com/${{github.repository}}/commit/${{steps.commitId.outputs.commitId}}
