name: test pull request
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'devl'
        required: true
        default: 'devl'
env:
 assignmentGroup: 'AE EDL Catalog Support'
 assignedTo: '${{github.event.pusher.name}}'
 #changeDescription: 'See Latest Commit https://github.deere.com/${{github.repository}}/commit/${{ env.GITHUB_SHA }}'
 configurationItem: 'aws-ae-databricks-prod.edl-databricks-sql-logs-job'

jobs:
 BuildAndTest:
   runs-on: ubuntu-latest 
   steps:
    - uses: actions/checkout@v2
    - name: Build Deployment
      run: |
        echo BuildTest
    - run: |
        echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV
        echo $assignmentGroup
        echo $assignedTo
        echo $changeDescription
        echo $configurationItem
        echo $GITHUB_SHA
        echo $GITHUB_SERVER_URL
        echo ${{ github.event.pusher.name }}
 DevDeploy:
   runs-on: ubuntu-latest 
   if: ${{ (github.event.ref == 'refs/heads/master' || github.event.inputs.environment == 'devl') }}
   needs: [BuildAndTest]
   steps:
    - uses: actions/checkout@v2
    - name: Build Deployment
      run: |
        echo Devl Deployment 
        echo ${{ github.event.pusher.name }}
 ProdDeploy:
    if: ${{ github.event.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest 
    needs: [BuildAndTest,DevDeploy]
    steps:
    - uses: actions/checkout@v2
    - run: echo Prod Deployment
    - name: Get commitId
      id: commitId
      run: echo "::set-output name=commitId::$(git log -n 1 --pretty=format:'%h')"
    - run: echo ${{ steps.commitId.outputs.commitId }}
    - run: echo https://github.com/${{github.repository}}/commit/${{steps.commitId.outputs.commitId}}
