name: test pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  if_merged:
    if: ${{ github.event.ref == 'refs/heads/master' }}
    runs-on:  ubuntu-latest 
    steps:
    - name: checkout
      run: echo checkout
    - name: "get pr url"  
      if: github.event.pull_request.merged == true
      run: |
        echo ${{ github.event.pull_request.url }}
