name: test pull request
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [master]
    types: [closed] 
  workflow_dispatch:
    inputs:
      environment:
        description: 'devl'
        required: true
        default: 'devl'
jobs:
  build:
    runs-on:  ubuntu-latest 
    steps:
    - run: echo "build" 
  devl:
    runs-on:  ubuntu-latest 
    if: ${{ (github.event.ref == 'refs/heads/master' || github.event.inputs.environment  == 'devl') }}
    steps:
    - run: echo "devl deployment"
  prod:
    if: github.event.pull_request.merged == true
    runs-on:  ubuntu-latest 
    steps:
    - name: checkout
      run: echo checkout
    - name: "get pr url"  
      run: |
        echo ${{ github.event.pull_request.url }}
