name: ReturnValue
on:
  push:
    branches: [ '*' ]
jobs:
 BuildAndTest:
   runs-on: ubuntu-latest 
   steps:
    - uses: actions/checkout@v2
    - name: node setup
      id: pokemon
      uses: sureshdec/ActionTemaplate/.github/actions/output@main
      with:
        pokemon_id: 5ddfs
    - run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
